### ISSUE TITLE
After installing the V6.1, The ROM becomes unusable [FIXED] | Charging stops at 70% 

### ISSUE THREAD

**Issue by yarida** [SPART4NICUS/Ares_7870#10]
ROM : CrDroid 6.7 [Astrako Build] / Any ROM
DEVICE : A320F
ISSUE : After installing the new version, the phone freezes and auto restarts
              I tried clean installing and sadly it didn't work, and I tried not 
             opening the phone and letting it load on its own, and didn't work
                too.
             Also, It has an Android System Error ( on some custom ROMS )

I will attach a kernel log here after I try it with other custom ROMS to see 
      If it has the same issue
[dmesg[1].log](https://github.com/SPART4NICUS/Ares_7870/files/4959921/dmesg.1.log)

**Comment by MrArtemSid** [comment]
U need to use H-Vendor instead of Treblue/Spaget

**Comment by yarida** [comment]
> U need to use H-Vendor instead of Treblue/Spaget

I already use H-Vendor because it is the supported build for the A320F variant

**Comment by MrArtemSid** [comment]
Strange, idk then. Everything is fine on J710FN

**Comment by yarida** [comment]
> Strange, idk then. Everything is fine on J710FN

Strange indeed. Well, I'll carry on then, I'll just wait for new updates to roll out
Thank you for answering and for contributing to the project

**Comment by yarida** [comment]
UPDATE : Confirmed Working now with the V6.2 Build
