### ISSUE TITLE
Charging only goes up to 70 or 77 in A320X

### ISSUE THREAD

**Issue by yarida** [SPART4NICUS/Ares_7870#5]
Device : A320X
ROM : Astrako's CrDroid V6.7
Kernel installed that has issue : 
V5.1
V6.0

After installing the new builds, charging only goes up to 70% but if I unplugged it then plug it again, it can go upto 77%

**Comment by yarida** [comment]
Tried charging while it's on recovery, I'll update when I charge it again, to see if the issue is fixed

**Comment by yarida** [comment]
nvm, I think it stops on 70% is because of this:

write /sys/devices/battery/ac_charge 1550 

in https://github.com/SPART4NICUS/Ares_7870/commit/c2ecf2a5f7b4f560011b927e8ede36d571dcaaf2#diff-567c25094e13de0602b703652a1688b9

**Comment by yarida** [comment]
Here is a log

**Comment by yarida** [comment]
Here is a log
[logcat_07-10-2020_19-53-27.txt](https://github.com/SPART4NICUS/Ares_7870/files/4902962/logcat_07-10-2020_19-53-27.txt)

**Comment by SPART4NICUS** [comment]
fixed in upcoming v6.1 release.
